version: '3'
services:

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
        volumes:
            - ./dist:/var/www
            - ./dockerConfig/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
